#!/usr/bin/env bash
# To configure a Nginx server to return a custom header on request

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# To configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# To change permissions to allow us to create files with ease in this directory
sudo chmod -R 755 /var/www

# Creating Index Page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Code to create a webpage for error 404
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# Code to redirect_me
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to create error page and add a redirect for error 404
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the Nginx server after settings update
service nginx restart
